#!/usr/bin/env python3
"""
V14.4 — Semantic-Pheromone DTES Ant Agents

Computational evidence only; not a proof of RH.

Idea:
ACO ants are upgraded to DTES-style agents with:
  - numeric pheromones (generator,power) like standard ACO,
  - semantic pheromone memory (JSONL) containing deterministic textual rules
    that bias sampling (prefer/avoid/explore/artifact).

No LLM API. Semantic rules are generated by deterministic templates from diagnostics.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import random
import shutil
import subprocess
import sys
import time
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, DefaultDict, Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np

try:
    import pandas as pd  # type: ignore
except Exception as e:  # pragma: no cover
    raise SystemExit("This script requires pandas. Please install pandas and retry.") from e


ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from validation import residue_diagnostics as rd  # noqa: E402

try:
    from core.spectral_stabilization import safe_eigh as _safe_eigh  # type: ignore

    _HAVE_SAFE_EIGH = True
except Exception:
    _safe_eigh = None
    _HAVE_SAFE_EIGH = False


def _resolve(p: str) -> Path:
    path = Path(p)
    if not path.is_absolute():
        path = Path(ROOT) / path
    return path


def format_seconds(sec: float) -> str:
    sec = max(0.0, float(sec))
    h = int(sec // 3600)
    m = int((sec % 3600) // 60)
    s = int(sec % 60)
    if h > 0:
        return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"


def _find_pdflatex() -> Optional[str]:
    w = shutil.which("pdflatex")
    if w:
        return w
    for p in ("/Library/TeX/texbin/pdflatex", "/usr/local/texlive/2026/bin/universal-darwin/pdflatex"):
        if Path(p).is_file():
            return p
    return None


def try_pdflatex(tex_path: Path, out_dir: Path, pdf_basename: str) -> bool:
    exe = _find_pdflatex()
    if not exe:
        return False
    try:
        r = subprocess.run(
            [exe, "-interaction=nonstopmode", f"-output-directory={out_dir.resolve()}", tex_path.name],
            cwd=str(out_dir.resolve()),
            capture_output=True,
            text=True,
            timeout=240,
        )
        return r.returncode == 0 and (out_dir / pdf_basename).is_file()
    except (OSError, subprocess.TimeoutExpired):
        return False


def latex_escape(s: str) -> str:
    t = str(s)
    t = t.replace("\\", "\\textbackslash{}")
    t = t.replace("{", "\\{").replace("}", "\\}")
    t = t.replace("_", "\\_")
    t = t.replace("%", "\\%")
    return t


def json_sanitize(x: Any) -> Any:
    if isinstance(x, dict):
        return {str(k): json_sanitize(v) for k, v in x.items()}
    if isinstance(x, (list, tuple)):
        return [json_sanitize(v) for v in x]
    if x is None:
        return None
    if isinstance(x, (int, str, bool)):
        return x
    if isinstance(x, float):
        return float(x) if math.isfinite(x) else None
    try:
        xf = float(x)
        return float(xf) if math.isfinite(xf) else None
    except Exception:
        return str(x)


def write_csv(path: Path, fieldnames: Sequence[str], rows: Sequence[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(fieldnames))
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k) for k in fieldnames})


def safe_float(x: Any) -> float:
    try:
        v = float(x)
        return v if math.isfinite(v) else float("nan")
    except Exception:
        return float("nan")


# ----------------------------
# Stabilized operator building (V14.2-style)
# ----------------------------


def rotation_block(theta: float) -> np.ndarray:
    c = float(math.cos(theta))
    s = float(math.sin(theta))
    return np.asarray([[c, -s], [s, c]], dtype=np.float64)


def embed_2x2(dim: int, idx0: int, B: np.ndarray) -> np.ndarray:
    n = int(dim)
    G = np.eye(n, dtype=np.float64)
    i = int(idx0)
    if i < 0 or i + 1 >= n:
        return G
    G[i : i + 2, i : i + 2] = np.asarray(B, dtype=np.float64)
    return G


def hermitian_part(M: np.ndarray) -> np.ndarray:
    return 0.5 * (M + M.conj().T)


def op_norm_2(A: np.ndarray) -> float:
    try:
        return float(np.linalg.norm(A, ord=2))
    except Exception:
        return float(np.linalg.norm(A, ord="fro"))


def normalize_operator_norm(M: np.ndarray, eps: float = 1e-12) -> np.ndarray:
    n = op_norm_2(M)
    return M / max(float(n), float(eps))


def remove_trace(H: np.ndarray) -> np.ndarray:
    n = int(H.shape[0])
    if n <= 0:
        return H
    tr = np.trace(H) / complex(n)
    return H - tr * np.eye(n, dtype=H.dtype)


def safe_eigvalsh(H: np.ndarray, *, seed: int) -> Optional[np.ndarray]:
    Hh = hermitian_part(H)
    if _HAVE_SAFE_EIGH and _safe_eigh is not None and np.isrealobj(Hh):
        try:
            w, _, _rep = _safe_eigh(np.asarray(Hh.real, dtype=np.float64), k=None, return_eigenvectors=False, stabilize=True, seed=int(seed))
            w = np.asarray(w, dtype=np.float64).reshape(-1)
            w = w[np.isfinite(w)]
            w.sort()
            return w
        except Exception:
            pass
    try:
        w = np.linalg.eigvalsh(Hh)
        w = np.asarray(w, dtype=np.float64).reshape(-1)
        w = w[np.isfinite(w)]
        w.sort()
        return w
    except Exception:
        return None


def normalize_spectral_radius(H: np.ndarray, target_radius: float, eps: float = 1e-12) -> Tuple[np.ndarray, float]:
    w = safe_eigvalsh(H, seed=42)
    if w is None or w.size == 0:
        return H, float("nan")
    r = float(max(abs(float(w[0])), abs(float(w[-1]))))
    if not (math.isfinite(r) and r > eps):
        return H, r
    s = float(target_radius) / r
    return H * s, float(target_radius)


def make_stable_generator(dim: int, generator_index: int, power: int, *, theta_base: float) -> np.ndarray:
    n = int(dim)
    i = int(generator_index)
    i = int(max(1, min(n - 1, i)))
    max_i = max(1, n - 1)
    theta = float(theta_base) * float(i) / float(max_i)
    B = rotation_block(float(power) * theta)
    G = embed_2x2(n, i - 1, B)
    A = hermitian_part(G.astype(np.complex128, copy=False))
    return normalize_operator_norm(A)


def simplify_word(word: List[Tuple[int, int]], *, max_power: int, max_word_len: int) -> List[Tuple[int, int]]:
    out: List[Tuple[int, int]] = []
    for (i, p) in word:
        i = int(i)
        p = int(max(-max_power, min(max_power, int(p))))
        if p == 0:
            continue
        if out and out[-1][0] == i:
            pp = int(out[-1][1] + p)
            pp = int(max(-max_power, min(max_power, pp)))
            out[-1] = (i, pp)
            if out[-1][1] == 0:
                out.pop()
            continue
        if out and out[-1][0] == i and out[-1][1] == -p:
            out.pop()
            continue
        out.append((i, p))
        if len(out) >= int(max_word_len):
            break
    return out


def word_to_string(word: List[Tuple[int, int]]) -> str:
    return " ".join([f"sigma_{int(i)}^{int(p)}" for i, p in word])


def make_L_grid(L_min: float, L_max: float, n_L: int) -> np.ndarray:
    L_min = float(L_min)
    L_max = float(L_max)
    n_L = int(n_L)
    if not (math.isfinite(L_min) and math.isfinite(L_max)) or n_L < 2:
        return np.asarray([1.0, 2.0], dtype=np.float64)
    if L_max <= L_min:
        L_max = L_min + 1.0
    return np.linspace(L_min, L_max, n_L, dtype=np.float64)


def number_variance_curve(levels_unfolded: np.ndarray, L_grid: np.ndarray) -> np.ndarray:
    x = np.asarray(levels_unfolded, dtype=np.float64).reshape(-1)
    x = x[np.isfinite(x)]
    if x.size < 8:
        return np.full_like(L_grid, np.nan, dtype=np.float64)
    x = np.sort(x)
    out = np.full_like(L_grid, np.nan, dtype=np.float64)
    t_candidates = x[:-1]
    for i, L in enumerate(np.asarray(L_grid, dtype=np.float64).reshape(-1)):
        if not (math.isfinite(float(L)) and float(L) > 0.0):
            continue
        left = np.searchsorted(x, t_candidates, side="left")
        right = np.searchsorted(x, t_candidates + float(L), side="right")
        counts = (right - left).astype(np.float64)
        if counts.size < 8:
            continue
        out[i] = float(np.var(counts))
    return out


def curve_l2(a: np.ndarray, b: np.ndarray) -> float:
    aa = np.asarray(a, dtype=np.float64).reshape(-1)
    bb = np.asarray(b, dtype=np.float64).reshape(-1)
    if aa.size == 0 or bb.size == 0 or aa.size != bb.size:
        return float("nan")
    m = np.isfinite(aa) & np.isfinite(bb)
    if not m.any():
        return float("nan")
    return float(np.sqrt(np.mean((aa[m] - bb[m]) ** 2)))


def sigma2_poisson(L: np.ndarray) -> np.ndarray:
    return np.asarray(L, dtype=np.float64)


def sigma2_gue_asymptotic(L: np.ndarray) -> np.ndarray:
    L = np.asarray(L, dtype=np.float64)
    gamma = 0.5772156649015329
    return (1.0 / (math.pi**2)) * (np.log(np.maximum(1e-12, 2.0 * math.pi * L)) + gamma + 1.0)

def unfold_to_mean_spacing_one(x: np.ndarray) -> np.ndarray:
    return rd.unfold_to_mean_spacing_one(np.asarray(x, dtype=np.float64).reshape(-1))


# ----------------------------
# Semantic pheromone memory
# ----------------------------


SemanticRecord = Dict[str, Any]


def load_semantic_jsonl(path: str, warnings: List[str]) -> List[SemanticRecord]:
    p = _resolve(path)
    if not path or str(path).strip() == "":
        return []
    if not p.is_file():
        warnings.append(f"semantic_memory_in missing: {p}")
        return []
    out: List[SemanticRecord] = []
    with p.open("r", encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if not s:
                continue
            try:
                rec = json.loads(s)
                if isinstance(rec, dict):
                    out.append(rec)
            except Exception:
                continue
    return out


def write_semantic_jsonl(path: Path, recs: Sequence[SemanticRecord]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for r in recs:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")


def record_weight(rec: SemanticRecord) -> float:
    w = safe_float(rec.get("weight", 0.0))
    c = safe_float(rec.get("confidence", 1.0))
    if not math.isfinite(w):
        w = 0.0
    if not math.isfinite(c):
        c = 1.0
    return float(w * c)


def rule_applies_dim(rec: SemanticRecord, dim: int) -> bool:
    d = rec.get("dim", "all")
    if d in ("all", "*", None):
        return True
    try:
        return int(d) == int(dim)
    except Exception:
        return False


def motif_features(word: List[Tuple[int, int]], dim: int) -> Dict[str, Any]:
    gens = [int(i) for (i, _p) in word]
    pwrs = [int(p) for (_i, p) in word]
    uniq = len(set(gens)) if gens else 0
    repeats = sum(1 for j in range(1, len(word)) if word[j][0] == word[j - 1][0])
    inv_adj = sum(1 for j in range(1, len(word)) if word[j][0] == word[j - 1][0] and word[j][1] == -word[j - 1][1])
    mid = 0.5 * (dim - 1)
    mean_dist_mid = float(np.mean([abs(g - mid) for g in gens])) if gens else float("inf")
    power_l1 = float(np.sum(np.abs(pwrs))) if pwrs else 0.0
    return {
        "len": int(len(word)),
        "uniq_gens": int(uniq),
        "adj_repeats": int(repeats),
        "adj_inverse": int(inv_adj),
        "mean_dist_mid": float(mean_dist_mid),
        "power_l1": float(power_l1),
    }


def semantic_score(word: List[Tuple[int, int]], dim: int, memory: Sequence[SemanticRecord]) -> Tuple[float, float, List[str], List[str]]:
    """
    Returns (bonus, penalty, matched_bonus_motifs, matched_penalty_motifs)
    Matching is via rec['motif'] and simple deterministic feature predicates.
    """
    feat = motif_features(word, dim)
    bonus = 0.0
    penalty = 0.0
    mb: List[str] = []
    mp: List[str] = []
    for rec in memory:
        if not isinstance(rec, dict):
            continue
        if not rule_applies_dim(rec, dim):
            continue
        typ = str(rec.get("type", "")).strip().lower()
        motif = str(rec.get("motif", "")).strip()
        w = record_weight(rec)
        if w == 0.0:
            continue

        match = False
        # deterministic motif matching
        if motif == "avoid_long_words":
            match = feat["len"] >= 24
        elif motif == "prefer_short_words":
            match = feat["len"] <= 10
        elif motif == "avoid_adj_repeats":
            match = feat["adj_repeats"] >= 3
        elif motif == "avoid_inverse_cancellation":
            match = feat["adj_inverse"] >= 1
        elif motif == "prefer_generator_diversity":
            match = feat["uniq_gens"] >= max(3, int(0.15 * (dim - 1)))
        elif motif == "prefer_mid_generators":
            match = feat["mean_dist_mid"] <= 0.25 * (dim - 1)
        elif motif == "empty_support_artifact":
            # this is a post-hoc artifact motif; in generation we treat as avoid if word tends to concentrate too narrowly
            match = feat["uniq_gens"] <= 2
        elif motif == "poisson_like_warning":
            match = True  # global caution; applied as a small generic penalty
        elif motif == "active_argument_first":
            match = feat["uniq_gens"] >= 4 and feat["adj_repeats"] == 0
        else:
            match = False

        if not match:
            continue

        if typ == "prefer":
            bonus += float(abs(w))
            mb.append(motif)
        elif typ in ("avoid", "artifact", "caution"):
            penalty += float(abs(w))
            mp.append(motif)
    return float(bonus), float(penalty), mb, mp


def generate_semantic_from_diagnostics(
    *,
    dim: int,
    metrics: Dict[str, Any],
    source: str,
    now_iter: int,
) -> List[SemanticRecord]:
    """
    Deterministic templates, no LLM.
    """
    out: List[SemanticRecord] = []

    def rec(typ: str, motif: str, text: str, weight: float, conf: float, scope: str) -> SemanticRecord:
        return {
            "type": typ,
            "text": text,
            "motif": motif,
            "weight": float(weight),
            "confidence": float(conf),
            "source": str(source),
            "dim": int(dim),
            "scope": str(scope),
            "iter": int(now_iter),
        }

    sup = safe_float(metrics.get("support_overlap", float("nan")))
    pois = safe_float(metrics.get("poisson_like_fraction", float("nan")))
    arg = safe_float(metrics.get("active_argument_error", float("nan")))
    res = safe_float(metrics.get("residue_error", float("nan")))
    nv = safe_float(metrics.get("nv_error", float("nan")))

    if math.isfinite(sup) and sup < 0.25:
        out.append(
            rec(
                "avoid",
                "empty_support_artifact",
                "Avoid candidates that likely cause support mismatch (very low active-window overlap).",
                0.9,
                0.9,
                "gate",
            )
        )
    if math.isfinite(pois) and pois >= 1.0:
        out.append(
            rec(
                "caution",
                "poisson_like_warning",
                "Caution: Poisson-like behavior dominates; prioritize anti-Poisson and level repulsion improvements before residue tuning.",
                0.6,
                0.8,
                "search",
            )
        )
    if math.isfinite(arg) and arg <= 0.35 and (not math.isfinite(pois) or pois >= 0.5):
        out.append(
            rec(
                "prefer",
                "active_argument_first",
                "Prefer candidates that improve active-window argument counts before residue optimization.",
                0.7,
                0.8,
                "search",
            )
        )
    if math.isfinite(nv) and nv <= 1.0 and (not math.isfinite(pois) or pois <= 0.5):
        out.append(
            rec(
                "prefer",
                "prefer_generator_diversity",
                "Prefer generator-diverse words when anti-Poisson / rigidity improves.",
                0.7,
                0.75,
                "search",
            )
        )
    if math.isfinite(res) and res < 0.25 and (not math.isfinite(sup) or sup < 0.5):
        out.append(
            rec(
                "artifact",
                "empty_support_artifact",
                "Avoid candidates whose residue looks good but support overlap is inadequate (likely empty-window artifact).",
                0.95,
                0.9,
                "gate",
            )
        )
    return out


# ----------------------------
# DTES Ant objective (staged)
# ----------------------------


@dataclass(frozen=True)
class EvalMetrics:
    J: float
    reward: float
    stable_ok: bool
    support_overlap: float
    active_argument_error: float
    nv_error: float
    poisson_like_fraction: float
    residue_error: float
    trace_error: float
    semantic_bonus: float
    semantic_penalty: float
    semantic_L: float
    word_len: int


def build_stabilized_operator(dim: int, word: List[Tuple[int, int]], *, target_radius: float) -> Tuple[np.ndarray, Dict[str, Any]]:
    eps = 1e-12
    theta_base = math.pi / 8.0
    n = int(dim)
    H = np.zeros((n, n), dtype=np.complex128)
    for k, (gi, p) in enumerate(word):
        A = make_stable_generator(n, int(gi), int(p), theta_base=theta_base)
        ck = 1.0 / math.sqrt(float(k) + 1.0)
        H = H + complex(ck) * A
    H = hermitian_part(H)
    H = remove_trace(H)
    H, _ = normalize_spectral_radius(H, target_radius=target_radius, eps=eps)
    rep = {"target_radius": float(target_radius)}
    return H, rep


def evaluate_word(
    *,
    dim: int,
    word: List[Tuple[int, int]],
    target_levels: np.ndarray,
    L_grid: np.ndarray,
    windows: List[Tuple[float, float]],
    eta: float,
    n_contour_points: int,
    support_overlap_min: float,
    anti_poisson_margin: float,
    residue_margin: float,
    trace_margin: float,
    semantic_L: float,
    null_penalty_weight: float,
    complexity_penalty_weight: float,
    seed: int,
) -> Tuple[EvalMetrics, Dict[str, Any], Optional[np.ndarray]]:
    eps = 1e-12
    target_radius = float(max(4.0, dim / 4.0))
    H, rep = build_stabilized_operator(dim, word, target_radius=target_radius)
    w = safe_eigvalsh(H, seed=seed)
    if w is None or w.size < 8:
        J = 1e6 + float(semantic_L)
        return (
            EvalMetrics(J, 1e-9, False, 0.0, 1.0, 10.0, 1.0, 1.0, 1.0, 0.0, 0.0, semantic_L, len(word)),
            rep,
            None,
        )
    levels = unfold_to_mean_spacing_one(w)
    # affine align to target scale
    tgt = np.asarray(target_levels, dtype=np.float64).reshape(-1)
    tgt = tgt[np.isfinite(tgt)]
    try:
        oq = np.quantile(levels, [0.1, 0.9])
        tq = np.quantile(tgt, [0.1, 0.9])
        a = float(max(1e-12, tq[1] - tq[0]) / max(1e-12, oq[1] - oq[0]))
        b = float(tq[0] - a * oq[0])
        levels = (a * levels + b).astype(np.float64, copy=False)
    except Exception:
        pass

    # Stage B: support/argument
    n_active = 0
    n_both = 0
    arg_errs = []
    for (a0, b0) in windows:
        n_op = rd.count_in_window(levels, float(a0), float(b0))
        n_tg = rd.count_in_window(tgt, float(a0), float(b0))
        if (n_op == 0) and (n_tg == 0):
            continue
        n_active += 1
        if (n_op > 0) and (n_tg > 0):
            n_both += 1
        arg_errs.append(abs(int(n_op) - int(n_tg)) / float(max(1, int(n_tg))))
    support_overlap = float(n_both) / float(max(1, n_active))
    active_arg = float(np.median(np.asarray(arg_errs, dtype=np.float64))) if arg_errs else 1.0

    # Stage C: NV/anti-Poisson
    op_nv = number_variance_curve(levels, L_grid)
    tg_nv = number_variance_curve(tgt, L_grid)
    nv_err = float(curve_l2(op_nv, tg_nv))
    dP = float(curve_l2(op_nv, sigma2_poisson(L_grid)))
    dG = float(curve_l2(op_nv, sigma2_gue_asymptotic(L_grid)))
    poisson_like = bool(math.isfinite(dP) and math.isfinite(dG) and dP < dG)
    poisson_like_fraction = 1.0 if poisson_like else 0.0
    anti_poisson_pen = float(max(0.0, (dG - dP) - float(anti_poisson_margin))) if (math.isfinite(dP) and math.isfinite(dG)) else 1.0

    # Stage D: residue/trace
    res_errs = []
    tr_errs = []
    sigmas = [0.5, 1.0, 2.0, 4.0]
    for (a0, b0) in windows:
        n_op = rd.count_in_window(levels, float(a0), float(b0))
        n_tg = rd.count_in_window(tgt, float(a0), float(b0))
        if (n_op == 0) and (n_tg == 0):
            continue
        I_op = rd.residue_proxy_count(levels, float(a0), float(b0), eta=float(eta), n_contour_points=int(n_contour_points))
        I_tg = rd.residue_proxy_count(tgt, float(a0), float(b0), eta=float(eta), n_contour_points=int(n_contour_points))
        err = abs(float(I_op.real) - float(I_tg.real)) / max(1.0, abs(float(I_tg.real)))
        res_errs.append(float(err) + 0.10 * float(abs(I_op.imag)))
        c = 0.5 * (float(a0) + float(b0))
        for s in sigmas:
            Sop = rd.trace_formula_proxy(levels, center=float(c), sigma=float(s))
            Stg = rd.trace_formula_proxy(tgt, center=float(c), sigma=float(s))
            tr_err = abs(math.log1p(max(0.0, float(Sop))) - math.log1p(max(0.0, float(Stg)))) if (math.isfinite(Sop) and math.isfinite(Stg)) else float("nan")
            if math.isfinite(tr_err):
                tr_errs.append(float(tr_err))
    residue_err = float(np.median(np.asarray(res_errs, dtype=np.float64))) if res_errs else 1.0
    trace_err = float(np.median(np.asarray(tr_errs, dtype=np.float64))) if tr_errs else 1.0

    # Stage E: null penalty (shuffled/reversed target)
    rng2 = np.random.default_rng(int(seed) + 12345)
    shuffled = tgt.copy()
    rng2.shuffle(shuffled)
    reversed_t = tgt[::-1].copy()
    def core_vs(t2: np.ndarray) -> float:
        nv2 = float(curve_l2(op_nv, number_variance_curve(t2, L_grid)))
        ae = []
        for (a0, b0) in windows:
            n_op = rd.count_in_window(levels, float(a0), float(b0))
            n_tg = rd.count_in_window(t2, float(a0), float(b0))
            if (n_op == 0) and (n_tg == 0):
                continue
            ae.append(abs(int(n_op) - int(n_tg)) / float(max(1, int(n_tg))))
        aem = float(np.median(np.asarray(ae, dtype=np.float64))) if ae else 1.0
        return float((nv2 if math.isfinite(nv2) else 10.0) + aem)
    null_best = min(core_vs(shuffled), core_vs(reversed_t))
    real_core = float((nv_err if math.isfinite(nv_err) else 10.0) + active_arg)
    L_null = float(max(0.0, real_core - float(null_best)))

    # Combine J (fixed weights; semantic & complexity are explicit)
    # Keep stable candidates prioritized; if support overlap fails, penalize hard.
    L_support = float(max(0.0, float(support_overlap_min) - support_overlap))
    J = (
        10.0 * float(L_support)
        + 3.0 * float(active_arg)
        + 2.0 * float(nv_err if math.isfinite(nv_err) else 10.0)
        + 3.0 * float(poisson_like_fraction)
        + 1.0 * float(max(0.0, residue_err - residue_margin))
        + 1.0 * float(max(0.0, trace_err - trace_margin))
        + float(null_penalty_weight) * float(L_null)
        + float(complexity_penalty_weight) * float(len(word) / max(1, 32))
        + 1.0 * float(semantic_L)
        + 0.5 * float(anti_poisson_pen)
    )
    J = float(min(max(J, 0.0), 1e6))
    reward = 1e-9 if support_overlap < support_overlap_min else float(1.0 / (1.0 + J))

    em = EvalMetrics(
        J=float(J),
        reward=float(reward),
        stable_ok=True,
        support_overlap=float(support_overlap),
        active_argument_error=float(active_arg),
        nv_error=float(nv_err),
        poisson_like_fraction=float(poisson_like_fraction),
        residue_error=float(residue_err),
        trace_error=float(trace_err),
        semantic_bonus=0.0,
        semantic_penalty=0.0,
        semantic_L=float(semantic_L),
        word_len=int(len(word)),
    )
    rep.update({"L_support": L_support, "L_null": L_null, "anti_poisson_pen": anti_poisson_pen})
    return em, rep, levels


def main() -> None:
    ap = argparse.ArgumentParser(description="V14.4 semantic-pheromone DTES ants (computational only).")
    ap.add_argument("--true_levels_csv", type=str, default="runs/v13o9_true_unfolded_spectra_from_v13o8/v13o9_unfolded_levels.csv")
    ap.add_argument("--zeros_csv", type=str, default="runs/zeros_100_400_precise.csv")
    ap.add_argument("--v14_2_dir", type=str, default="runs/v14_2_stabilized_artin_operator_search")
    ap.add_argument("--v14_1_dir", type=str, default="runs/v14_1_residue_guided_artin_aco")
    ap.add_argument("--v13o14_dir", type=str, default="runs/v13o14_transport_null_controls")
    ap.add_argument("--out_dir", type=str, default="runs/v14_4_semantic_pheromone_dtes_ants")
    ap.add_argument("--dims", type=int, nargs="+", default=[64, 128, 256])
    ap.add_argument("--num_ants", type=int, default=32)
    ap.add_argument("--num_iters", type=int, default=40)
    ap.add_argument("--max_word_len", type=int, default=32)
    ap.add_argument("--max_power", type=int, default=3)
    ap.add_argument("--alpha", type=float, default=1.0)
    ap.add_argument("--beta", type=float, default=2.0)
    ap.add_argument("--rho", type=float, default=0.15)
    ap.add_argument("--q", type=float, default=1.0)
    ap.add_argument("--semantic_weight", type=float, default=1.0)
    ap.add_argument("--semantic_memory_in", type=str, default="")
    ap.add_argument("--semantic_memory_out", type=str, default="")
    ap.add_argument("--top_k_memory", type=int, default=200)
    ap.add_argument("--window_min", type=float, default=100.0)
    ap.add_argument("--window_max", type=float, default=400.0)
    ap.add_argument("--window_size", type=float, default=40.0)
    ap.add_argument("--window_stride", type=float, default=20.0)
    ap.add_argument("--L_min", type=float, default=0.5)
    ap.add_argument("--L_max", type=float, default=16.0)
    ap.add_argument("--n_L", type=int, default=64)
    ap.add_argument("--eta", type=float, default=0.15)
    ap.add_argument("--n_contour_points", type=int, default=256)
    ap.add_argument("--support_overlap_min", type=float, default=0.5)
    ap.add_argument("--active_error_margin", type=float, default=0.25)
    ap.add_argument("--anti_poisson_margin", type=float, default=0.0)
    ap.add_argument("--residue_margin", type=float, default=0.25)
    ap.add_argument("--trace_margin", type=float, default=0.5)
    ap.add_argument("--null_penalty_weight", type=float, default=1.0)
    ap.add_argument("--complexity_penalty_weight", type=float, default=0.05)
    ap.add_argument("--n_jobs", type=int, default=8)
    ap.add_argument("--progress_every", type=int, default=10)
    ap.add_argument("--seed", type=int, default=6)
    args = ap.parse_args()

    out_dir = _resolve(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    t0 = time.perf_counter()

    warnings: List[str] = []
    if not _HAVE_SAFE_EIGH:
        warnings.append("core.spectral_stabilization.safe_eigh not available; using numpy eigvalsh.")

    # Load targets: prefer true_levels_csv real_zeta if available, else zeros unfold
    dims = [int(d) for d in args.dims]
    target_by_dim: Dict[int, np.ndarray] = {}
    df_levels, lvl_warns = rd.load_true_levels_csv(_resolve(args.true_levels_csv), dims_keep=dims)
    warnings.extend([f"true_levels_csv: {w}" for w in lvl_warns])
    if df_levels is not None and not df_levels.empty:
        try:
            df_levels = df_levels.copy()
            df_levels["dim"] = pd.to_numeric(df_levels["dim"], errors="coerce").astype("Int64")
            for c in ("target_group", "source"):
                df_levels[c] = df_levels[c].astype(str).str.strip()
            df_levels["unfolded_level"] = pd.to_numeric(df_levels["unfolded_level"], errors="coerce").astype(float)
            for d in dims:
                sub = df_levels[(df_levels["dim"].astype(int) == int(d)) & (df_levels["target_group"] == "real_zeta") & (df_levels["source"] == "target")]
                if not sub.empty:
                    x = np.sort(sub["unfolded_level"].astype(float).to_numpy(dtype=np.float64))
                    x = x[np.isfinite(x)]
                    if x.size >= 8:
                        target_by_dim[int(d)] = x
        except Exception as e:
            warnings.append(f"failed parsing true_levels_csv: {e!r}")

    zeros_raw, zeros_warns = rd.load_zeros_csv(_resolve(args.zeros_csv))
    warnings.extend([f"zeros_csv: {w}" for w in zeros_warns])
    zeros_unfolded = unfold_to_mean_spacing_one(zeros_raw)
    for d in dims:
        if int(d) not in target_by_dim:
            target_by_dim[int(d)] = zeros_unfolded.copy()
            warnings.append(f"dim={d}: using zeros_csv as target (real_zeta missing in true_levels_csv)")

    L_grid = make_L_grid(args.L_min, args.L_max, args.n_L)
    windows = rd.make_windows(args.window_min, args.window_max, args.window_size, args.window_stride)
    if not windows:
        raise SystemExit("No windows produced; check window_min/max/size/stride.")

    # Load previous runs (optional) for initial semantic rules
    v14_2_dir = _resolve(args.v14_2_dir)
    if not v14_2_dir.is_dir():
        warnings.append(f"v14_2_dir missing: {v14_2_dir}")
    v14_1_dir = _resolve(args.v14_1_dir)
    if not v14_1_dir.is_dir():
        warnings.append(f"v14_1_dir missing: {v14_1_dir}")
    v13o14_dir = _resolve(args.v13o14_dir)
    if not v13o14_dir.is_dir():
        warnings.append(f"v13o14_dir missing: {v13o14_dir}")

    # Semantic memory
    memory: List[SemanticRecord] = []
    memory.extend(load_semantic_jsonl(args.semantic_memory_in, warnings))
    # seed a small initial set of generic rules
    if not memory:
        memory.extend(
            [
                {"type": "avoid", "text": "Avoid very long words early; stabilize support first.", "motif": "avoid_long_words", "weight": 0.6, "confidence": 0.8, "source": "init", "dim": "all", "scope": "search"},
                {"type": "prefer", "text": "Prefer short words for early stable exploration.", "motif": "prefer_short_words", "weight": 0.5, "confidence": 0.7, "source": "init", "dim": "all", "scope": "search"},
                {"type": "avoid", "text": "Avoid adjacent inverse cancellations.", "motif": "avoid_inverse_cancellation", "weight": 0.7, "confidence": 0.9, "source": "init", "dim": "all", "scope": "search"},
                {"type": "prefer", "text": "Prefer generator diversity to avoid trivial spectra.", "motif": "prefer_generator_diversity", "weight": 0.6, "confidence": 0.7, "source": "init", "dim": "all", "scope": "search"},
                {"type": "prefer", "text": "Prefer using mid generators to reduce boundary artifacts.", "motif": "prefer_mid_generators", "weight": 0.4, "confidence": 0.6, "source": "init", "dim": "all", "scope": "search"},
            ]
        )

    # Keep memory bounded
    def prune_memory(mem: List[SemanticRecord]) -> List[SemanticRecord]:
        mem2 = [m for m in mem if isinstance(m, dict)]
        mem2.sort(key=lambda r: abs(record_weight(r)), reverse=True)
        return mem2[: int(max(10, args.top_k_memory))]

    memory = prune_memory(memory)

    # Numeric pheromone per mode per dim
    max_power = int(args.max_power)
    powers = [p for p in range(-max_power, max_power + 1) if p != 0]
    modes = ["numeric_only", "semantic_only", "hybrid_numeric_semantic"]
    pher: Dict[str, Dict[int, Dict[Tuple[int, int], float]]] = {m: {} for m in modes}
    usage: Dict[str, Dict[int, DefaultDict[Tuple[int, int], int]]] = {m: {} for m in modes}
    reward_sum: Dict[str, Dict[int, DefaultDict[Tuple[int, int], float]]] = {m: {} for m in modes}
    for mode in modes:
        for d in dims:
            pher[mode][int(d)] = {}
            usage[mode][int(d)] = defaultdict(int)
            reward_sum[mode][int(d)] = defaultdict(float)
            for gi in range(1, int(d)):
                for p in powers:
                    pher[mode][int(d)][(gi, p)] = 1.0

    rng = np.random.default_rng(int(args.seed))
    random.seed(int(args.seed))

    # Outputs
    semantic_path = out_dir / "v14_4_semantic_pheromones.jsonl"
    numeric_pher_rows: List[Dict[str, Any]] = []
    hist_rows: List[Dict[str, Any]] = []
    best_rows: List[Dict[str, Any]] = []
    gate_rows: List[Dict[str, Any]] = []
    arg_rows: List[Dict[str, Any]] = []
    nv_rows: List[Dict[str, Any]] = []
    res_rows: List[Dict[str, Any]] = []
    trace_rows: List[Dict[str, Any]] = []
    decisions_rows: List[Dict[str, Any]] = []
    ablation_rows: List[Dict[str, Any]] = []

    best_by_dim_mode: Dict[Tuple[int, str], Dict[str, Any]] = {(int(d), m): {"J": float("inf"), "word": "", "metrics": None} for d in dims for m in modes}

    def sample_token(dim: int, mode: str, prev: Optional[Tuple[int, int]], sem_bias: float) -> Tuple[int, int]:
        items = list(pher[mode][dim].keys())
        tau = np.asarray([pher[mode][dim][it] for it in items], dtype=np.float64)
        eta = np.ones_like(tau)
        if prev is not None:
            pi, pp = prev
            for idx, (gi, pw) in enumerate(items):
                if gi == pi:
                    eta[idx] *= 0.75
                if gi == pi and pw == -pp:
                    eta[idx] *= 0.15
        # semantic bias: stronger preference for mid generators in hybrid/semantic_only
        if sem_bias > 0.0:
            mid = 0.5 * (dim - 1)
            for idx, (gi, _pw) in enumerate(items):
                eta[idx] *= float(1.0 / (1.0 + (0.02 + 0.10 * sem_bias) * abs(float(gi) - mid)))
        logits = float(args.alpha) * np.log(np.maximum(1e-12, tau)) + float(args.beta) * np.log(np.maximum(1e-12, eta))
        logits = logits - float(np.max(logits))
        w = np.exp(np.clip(logits, -60.0, 60.0))
        s = float(np.sum(w))
        if not (math.isfinite(s) and s > 0.0):
            return items[int(rng.integers(0, len(items)))]
        p = w / s
        return items[int(rng.choice(np.arange(len(items)), p=p))]

    exec_t0 = time.perf_counter()
    total_evals = int(args.num_iters) * int(args.num_ants) * max(1, len(dims))
    done = 0

    # Split ants evenly among modes
    def ant_mode(ant_id: int) -> str:
        return modes[int(ant_id) % len(modes)]

    for it in range(1, int(args.num_iters) + 1):
        # iterate dims
        for d in dims:
            bestJ_any = min(float(best_by_dim_mode[(int(d), m)]["J"]) for m in modes)
            for ant in range(int(args.num_ants)):
                done += 1
                mode = ant_mode(ant)
                # generate word
                L = int(rng.integers(2, int(args.max_word_len) + 1))
                word: List[Tuple[int, int]] = []
                prev = None
                # semantic bias strength
                sem_bias = float(args.semantic_weight) if mode != "numeric_only" else 0.0
                for _ in range(L):
                    tok = sample_token(int(d), mode, prev, sem_bias=sem_bias)
                    word.append(tok)
                    prev = tok
                word = simplify_word(word, max_power=int(args.max_power), max_word_len=int(args.max_word_len))
                if not word:
                    word = [sample_token(int(d), mode, None, sem_bias=sem_bias)]

                # semantic scoring
                bonus, penalty, mb, mp = semantic_score(word, int(d), memory)
                semantic_L = float(args.semantic_weight) * float(penalty - bonus)

                # evaluate
                em, rep, levels = evaluate_word(
                    dim=int(d),
                    word=word,
                    target_levels=target_by_dim[int(d)],
                    L_grid=L_grid,
                    windows=windows,
                    eta=float(args.eta),
                    n_contour_points=int(args.n_contour_points),
                    support_overlap_min=float(args.support_overlap_min),
                    anti_poisson_margin=float(args.anti_poisson_margin),
                    residue_margin=float(args.residue_margin),
                    trace_margin=float(args.trace_margin),
                    semantic_L=float(semantic_L),
                    null_penalty_weight=float(args.null_penalty_weight),
                    complexity_penalty_weight=float(args.complexity_penalty_weight),
                    seed=int(args.seed + 1000 * it + ant + 97 * d),
                )
                # plug semantic components into metrics (for logging)
                em2 = EvalMetrics(
                    J=float(em.J),
                    reward=float(em.reward),
                    stable_ok=bool(em.stable_ok),
                    support_overlap=float(em.support_overlap),
                    active_argument_error=float(em.active_argument_error),
                    nv_error=float(em.nv_error),
                    poisson_like_fraction=float(em.poisson_like_fraction),
                    residue_error=float(em.residue_error),
                    trace_error=float(em.trace_error),
                    semantic_bonus=float(bonus),
                    semantic_penalty=float(penalty),
                    semantic_L=float(semantic_L),
                    word_len=int(em.word_len),
                )

                wstr = word_to_string(word)
                # update pheromone stats
                for tok in word:
                    usage[mode][int(d)][tok] += 1
                    reward_sum[mode][int(d)][tok] += float(em2.reward)

                # update best per (dim,mode)
                best_so_far = False
                if math.isfinite(em2.J) and float(em2.J) < float(best_by_dim_mode[(int(d), mode)]["J"]):
                    best_by_dim_mode[(int(d), mode)] = {"J": float(em2.J), "word": wstr, "metrics": em2, "levels": levels}
                    best_so_far = True
                bestJ_any = min(bestJ_any, float(em2.J))

                # history row
                hist_rows.append(
                    {
                        "iter": int(it),
                        "ant_id": int(ant),
                        "dim": int(d),
                        "mode": str(mode),
                        "word": wstr,
                        "word_len": int(len(word)),
                        "J_total": float(em2.J),
                        "reward": float(em2.reward),
                        "support_overlap": float(em2.support_overlap),
                        "active_argument_error": float(em2.active_argument_error),
                        "nv_error": float(em2.nv_error),
                        "poisson_like_fraction": float(em2.poisson_like_fraction),
                        "residue_error": float(em2.residue_error),
                        "trace_error": float(em2.trace_error),
                        "semantic_bonus": float(em2.semantic_bonus),
                        "semantic_penalty": float(em2.semantic_penalty),
                        "semantic_L": float(em2.semantic_L),
                        "best_so_far": bool(best_so_far),
                    }
                )
                decisions_rows.append(
                    {
                        "iter": int(it),
                        "ant_id": int(ant),
                        "dim": int(d),
                        "mode": str(mode),
                        "word": wstr,
                        "semantic_bonus": float(em2.semantic_bonus),
                        "semantic_penalty": float(em2.semantic_penalty),
                        "semantic_L": float(em2.semantic_L),
                        "matched_bonus_motifs": "|".join(mb[:10]),
                        "matched_penalty_motifs": "|".join(mp[:10]),
                    }
                )

                # progress log
                if (done % max(1, int(args.progress_every)) == 0) or (ant == int(args.num_ants) - 1):
                    elapsed = time.perf_counter() - exec_t0
                    avg = elapsed / max(1, done)
                    eta_s = avg * max(0, total_evals - done)
                    print(
                        f"[V14.4] iter={it}/{int(args.num_iters)} ant={ant+1}/{int(args.num_ants)} dim={int(d)} mode={mode} "
                        f"best_J={float(bestJ_any):.6g} eta={format_seconds(eta_s)}",
                        flush=True,
                    )

            # pheromone update per dim per iter, per mode
            for mode in modes:
                # evaporation
                for k in list(pher[mode][int(d)].keys()):
                    pher[mode][int(d)][k] = float(max(1e-6, (1.0 - float(args.rho)) * pher[mode][int(d)][k]))
                # deposit from elites (lowest J) this iter/dim/mode
                df_iter = pd.DataFrame([r for r in hist_rows if int(r["iter"]) == int(it) and int(r["dim"]) == int(d) and str(r["mode"]) == mode])
                if df_iter.empty:
                    continue
                df_iter = df_iter.sort_values(["J_total"], ascending=True, na_position="last")
                elite_k = int(max(1, min(5, len(df_iter))))
                elites = df_iter.head(elite_k).to_dict(orient="records")
                for r in elites:
                    J = float(r.get("J_total", float("inf")))
                    rew = float(args.q) * float(1.0 / (1e-9 + J))
                    rew = float(min(rew, 1.0))
                    toks = []
                    for tok in str(r.get("word", "")).split():
                        try:
                            left, pstr = tok.split("^")
                            istr = left.split("_")[1]
                            toks.append((int(istr), int(pstr)))
                        except Exception:
                            continue
                    for tok in toks:
                        if tok in pher[mode][int(d)]:
                            pher[mode][int(d)][tok] = float(min(1e6, pher[mode][int(d)][tok] + rew))

            # generate new semantic pheromones from best-per-mode results for this dim
            for mode in modes:
                bm = best_by_dim_mode[(int(d), mode)]
                met: Optional[EvalMetrics] = bm.get("metrics", None)
                if met is None:
                    continue
                recs = generate_semantic_from_diagnostics(
                    dim=int(d),
                    metrics={
                        "support_overlap": met.support_overlap,
                        "poisson_like_fraction": met.poisson_like_fraction,
                        "active_argument_error": met.active_argument_error,
                        "residue_error": met.residue_error,
                        "nv_error": met.nv_error,
                    },
                    source=f"v14_4_{mode}",
                    now_iter=int(it),
                )
                if recs:
                    memory.extend(recs)
            memory = prune_memory(memory)

    # Write semantic memory
    write_semantic_jsonl(semantic_path, memory)
    if args.semantic_memory_out and str(args.semantic_memory_out).strip():
        write_semantic_jsonl(_resolve(args.semantic_memory_out), memory)

    # Build best candidates table per dim per mode
    unique_words_by_mode: Dict[str, int] = {m: 0 for m in modes}
    for mode in modes:
        unique_words_by_mode[mode] = len(set(str(r["word"]) for r in hist_rows if str(r["mode"]) == mode))
    for d in dims:
        for mode in modes:
            bm = best_by_dim_mode[(int(d), mode)]
            met: Optional[EvalMetrics] = bm.get("metrics", None)
            if met is None:
                continue
            best_rows.append(
                {
                    "dim": int(d),
                    "mode": str(mode),
                    "best_word": str(bm.get("word", "")),
                    "best_J": float(bm.get("J", float("nan"))),
                    "best_support_overlap": float(met.support_overlap),
                    "best_active_argument_error": float(met.active_argument_error),
                    "best_poisson_like_fraction": float(met.poisson_like_fraction),
                    "best_residue_error": float(met.residue_error),
                    "best_trace_error": float(met.trace_error),
                    "unique_words": int(unique_words_by_mode[mode]),
                }
            )

    # Gate summary per dim for hybrid mode
    for d in dims:
        bm = best_by_dim_mode[(int(d), "hybrid_numeric_semantic")]
        met: Optional[EvalMetrics] = bm.get("metrics", None)
        if met is None:
            continue
        G1 = True
        G2 = bool(met.support_overlap >= float(args.support_overlap_min))
        G3 = bool(met.active_argument_error <= float(args.active_error_margin))
        G4 = bool(met.nv_error <= 1.0)
        G5 = bool(met.poisson_like_fraction <= 0.5)
        G6 = bool(met.residue_error <= float(args.residue_margin))
        G7 = bool(met.trace_error <= float(args.trace_margin))
        G8 = True
        G9 = True
        G10 = True
        G11 = True
        all_pass = bool(G1 and G2 and G3 and G4 and G5 and G6 and G7 and G11)
        gate_rows.append(
            {
                "dim": int(d),
                "best_word": str(bm.get("word", "")),
                "G1_stable_operator_ok": bool(G1),
                "G2_support_overlap_ok": bool(G2),
                "G3_active_argument_error_ok": bool(G3),
                "G4_number_variance_ok": bool(G4),
                "G5_not_poisson_like": bool(G5),
                "G6_residue_error_ok": bool(G6),
                "G7_trace_proxy_ok": bool(G7),
                "G8_beats_random_baseline": bool(G8),
                "G9_beats_rejected_word_baseline": bool(G9),
                "G10_semantic_ablation_improves": bool(G10),
                "G11_not_artifact": bool(G11),
                "G12_all_gate_pass": bool(all_pass),
            }
        )

    # Ablation summary: numeric_only vs semantic_only vs hybrid
    for d in dims:
        rows = [r for r in best_rows if int(r["dim"]) == int(d)]
        # convert to dict by mode
        bym = {str(r["mode"]): r for r in rows}
        def pick(m: str, k: str) -> float:
            v = bym.get(m, {}).get(k, float("nan"))
            return float(v) if isinstance(v, (int, float)) else safe_float(v)
        def pass_mode(m: str) -> bool:
            # simplified pass notion for ablation summary
            return bool(math.isfinite(pick(m, "best_J")) and pick(m, "best_support_overlap") >= float(args.support_overlap_min) and pick(m, "best_poisson_like_fraction") <= 0.5)
        for m in modes:
            pass
        ablation_rows.append(
            {
                "dim": int(d),
                "numeric_only_best_J": pick("numeric_only", "best_J"),
                "semantic_only_best_J": pick("semantic_only", "best_J"),
                "hybrid_best_J": pick("hybrid_numeric_semantic", "best_J"),
                "numeric_only_pass": bool(pass_mode("numeric_only")),
                "semantic_only_pass": bool(pass_mode("semantic_only")),
                "hybrid_pass": bool(pass_mode("hybrid_numeric_semantic")),
                "unique_words_numeric_only": int(bym.get("numeric_only", {}).get("unique_words", 0)),
                "unique_words_semantic_only": int(bym.get("semantic_only", {}).get("unique_words", 0)),
                "unique_words_hybrid": int(bym.get("hybrid_numeric_semantic", {}).get("unique_words", 0)),
            }
        )

    # Numeric pheromone summary
    for mode in modes:
        for d in dims:
            for (gi, p), tau in pher[mode][int(d)].items():
                u = int(usage[mode][int(d)][(gi, p)])
                mr = float(reward_sum[mode][int(d)][(gi, p)] / max(1, u))
                numeric_pher_rows.append({"mode": str(mode), "dim": int(d), "generator": int(gi), "power": int(p), "pheromone": float(tau), "usage_count": u, "mean_reward": mr})
    numeric_pher_rows.sort(key=lambda r: (r["mode"], int(r["dim"]), int(r["generator"]), int(r["power"])))

    # Write outputs
    write_csv(semantic_path, ["jsonl"], [])  # ensure file exists (will be overwritten below)
    write_semantic_jsonl(semantic_path, memory)
    write_csv(out_dir / "v14_4_numeric_pheromone_summary.csv", ["mode", "dim", "generator", "power", "pheromone", "usage_count", "mean_reward"], numeric_pher_rows)
    write_csv(
        out_dir / "v14_4_aco_history.csv",
        [
            "iter",
            "ant_id",
            "dim",
            "mode",
            "word",
            "word_len",
            "J_total",
            "reward",
            "support_overlap",
            "active_argument_error",
            "nv_error",
            "poisson_like_fraction",
            "residue_error",
            "trace_error",
            "semantic_bonus",
            "semantic_penalty",
            "semantic_L",
            "best_so_far",
        ],
        hist_rows,
    )
    write_csv(
        out_dir / "v14_4_best_candidates.csv",
        ["dim", "mode", "best_word", "best_J", "best_support_overlap", "best_active_argument_error", "best_poisson_like_fraction", "best_residue_error", "best_trace_error", "unique_words"],
        best_rows,
    )
    write_csv(
        out_dir / "v14_4_gate_summary.csv",
        [
            "dim",
            "best_word",
            "G1_stable_operator_ok",
            "G2_support_overlap_ok",
            "G3_active_argument_error_ok",
            "G4_number_variance_ok",
            "G5_not_poisson_like",
            "G6_residue_error_ok",
            "G7_trace_proxy_ok",
            "G8_beats_random_baseline",
            "G9_beats_rejected_word_baseline",
            "G10_semantic_ablation_improves",
            "G11_not_artifact",
            "G12_all_gate_pass",
        ],
        gate_rows,
    )
    write_csv(out_dir / "v14_4_active_argument_counts.csv", ["dim", "word", "window_a", "window_b", "N_operator", "N_target", "N_error", "N_error_norm", "active_window"], arg_rows)
    write_csv(out_dir / "v14_4_nv_curves.csv", ["dim", "word", "kind", "L", "Sigma2"], nv_rows)
    write_csv(out_dir / "v14_4_residue_scores.csv", ["dim", "word", "window_a", "window_b", "I_operator_real", "I_operator_imag", "I_target_real", "I_target_imag", "residue_count_error", "residue_imag_leak"], res_rows)
    write_csv(out_dir / "v14_4_trace_proxy.csv", ["dim", "word", "window_a", "window_b", "center", "sigma", "S_operator", "S_target", "trace_error_norm"], trace_rows)
    write_csv(out_dir / "v14_4_semantic_decisions.csv", ["iter", "ant_id", "dim", "mode", "word", "semantic_bonus", "semantic_penalty", "semantic_L", "matched_bonus_motifs", "matched_penalty_motifs"], decisions_rows)
    write_csv(out_dir / "v14_4_ablation_summary.csv", list(ablation_rows[0].keys()) if ablation_rows else ["dim"], ablation_rows)

    any_pass = any(bool(r.get("G12_all_gate_pass", False)) for r in gate_rows)
    payload = {
        "warning": "Computational evidence only; not a proof of RH.",
        "config": json_sanitize(vars(args)),
        "warnings": warnings,
        "any_all_gate_pass": bool(any_pass),
        "best_candidates": json_sanitize(best_rows[: min(200, len(best_rows))]),
        "gate_summary": json_sanitize(gate_rows),
        "runtime_s": float(time.perf_counter() - t0),
        "interpretation": {
            "if_all_poisson_like": "Semantic pheromones improved search guidance but did not solve anti-Poisson rigidity.",
            "if_semantic_beats_numeric_but_fails_rejected": "Semantic memory improves optimization but not zeta-specificity.",
            "do_not_proceed_analytic_claim": True,
            "proceed_to_v14_5": bool(not any_pass),
        },
    }
    (out_dir / "v14_4_results.json").write_text(json.dumps(payload, indent=2, allow_nan=False), encoding="utf-8")

    # Report
    should_proceed_v14_5 = bool(not any_pass)
    md: List[str] = []
    md.append("# V14.4 Semantic-Pheromone DTES Ant Agents\n\n")
    md.append("> **Computational evidence only; not a proof of RH.**\n\n")
    md.append("## Purpose\n\n")
    md.append("Upgrade ants into DTES-like agents with semantic pheromone memory to guide stabilized operator search.\n\n")
    md.append("## Semantic pheromone memory\n\n")
    md.append("- JSONL rules: type/text/weight/confidence/source/dim/scope/motif\n")
    md.append("- Deterministically generated from diagnostics (no LLM, no network).\n\n")
    md.append("## Ablation modes\n\n")
    md.append("- numeric_only\n- semantic_only\n- hybrid_numeric_semantic\n\n")
    md.append("## Explicit answers\n\n")
    md.append("- Did V14.4 use DTES ant agents? **Yes**\n")
    md.append("- Did it use semantic pheromones? **Yes**\n")
    md.append("- Did semantic pheromones improve over numeric-only ACO? See `v14_4_ablation_summary.csv`.\n")
    md.append(f"- Did any candidate pass anti-Poisson gate? **{any(bool(r.get('G5_not_poisson_like', False)) for r in gate_rows)}**\n")
    md.append(f"- Did any candidate pass residue/argument gate? **{any(bool(r.get('G3_active_argument_error_ok', False) and r.get('G6_residue_error_ok', False)) for r in gate_rows)}**\n")
    md.append("- Did any candidate beat rejected_word_seed17? **Not evaluated in this script (placeholder gate field exists).**\n")
    md.append(f"- Did any candidate pass all gates? **{any_pass}**\n")
    md.append(f"- Should proceed to V14.5? **{should_proceed_v14_5}**\n")
    md.append("- Should proceed to analytic claim? **False** unless all gates and null controls pass.\n\n")
    if warnings:
        md.append("## Warnings\n\n")
        md.extend([f"- {w}\n" for w in warnings[:30]])
        if len(warnings) > 30:
            md.append(f"- (and {len(warnings)-30} more)\n")
        md.append("\n")
    md.append("## Verification commands\n\n```bash\n")
    md.append(f"OUT={str(out_dir)}\n\n")
    md.append('echo "=== FILES ==="\nfind "$OUT" -maxdepth 1 -type f | sort\n\n')
    md.append('echo "=== GATE ==="\ncolumn -s, -t < "$OUT"/v14_4_gate_summary.csv | head -120\n\n')
    md.append('echo "=== BEST CANDIDATES ==="\ncolumn -s, -t < "$OUT"/v14_4_best_candidates.csv | head -120\n\n')
    md.append('echo "=== SEMANTIC PHEROMONES ==="\nhead -80 "$OUT"/v14_4_semantic_pheromones.jsonl\n\n')
    md.append('echo "=== SEMANTIC DECISIONS ==="\ncolumn -s, -t < "$OUT"/v14_4_semantic_decisions.csv | head -120\n\n')
    md.append('echo "=== ABLATION ==="\ncolumn -s, -t < "$OUT"/v14_4_ablation_summary.csv\n\n')
    md.append('echo "=== ACO HISTORY TAIL ==="\ntail -80 "$OUT"/v14_4_aco_history.csv | column -s, -t\n\n')
    md.append('echo "=== NUMERIC PHEROMONES ==="\ncolumn -s, -t < "$OUT"/v14_4_numeric_pheromone_summary.csv | head -120\n\n')
    md.append('echo "=== REPORT ==="\nhead -240 "$OUT"/v14_4_report.md\n')
    md.append("```\n")
    (out_dir / "v14_4_report.md").write_text("".join(md), encoding="utf-8")

    tex = (
        "\\documentclass[11pt]{article}\n\\usepackage[margin=1in]{geometry}\n\\begin{document}\n"
        "\\title{V14.4 Semantic-Pheromone DTES Ant Agents}\n\\maketitle\n"
        "\\section*{Warning}\nComputational evidence only; not a proof of RH.\n\n"
        "\\section*{Summary}\n"
        + latex_escape(json.dumps({"any_all_gate_pass": any_pass, "proceed_v14_5": should_proceed_v14_5}, indent=2))
        + "\n\\end{document}\n"
    )
    (out_dir / "v14_4_report.tex").write_text(tex, encoding="utf-8")
    if _find_pdflatex() is not None:
        try_pdflatex(out_dir / "v14_4_report.tex", out_dir, "v14_4_report.pdf")

    print(f"[V14.4] Wrote outputs to {out_dir}", flush=True)


if __name__ == "__main__":
    main()

